infrastructures:
    baremetal: {}

nodes:
    'puppetmaster.example.com':
        type: 'baremetal'
    'broker.example.com':
        type: 'baremetal'
    'linux01.example.com':
        type: 'baremetal'

plan:
    max_in_flight: 3
    ssh_root_pass: 'vagrant'

steps:
    - name: "Make sure all machines are up"
      nodes:
        - 'puppetmaster.example.com'
      command:
          plugin: 'custom'
          exec: 'vagrant'
          arguments: 'up'

    - name: "Provision Mcollective broker machine"
      nodes:
        - 'broker.example.com'
        - 'linux01.example.com'
      command:
          plugin: 'ssh/puppet_agent_run'
          verify_commands:
              - plugin: 'ssh/file_contains'
                file: '/etc/puppet/puppet.conf'
                pattern: 'puppetmaster.example.com'
          arguments:
            '--server': 'puppetmaster.example.com'
            '--waitforcert': '300'
